/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author David Reyes
 */
public class MenuGUI extends javax.swing.JFrame {

    private String tipo_usuario;
    public MenuGUI() {
        initComponents();
    }
    
    public MenuGUI(String tipo_usuario) {
        this.tipo_usuario = tipo_usuario;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jp_cuerpo = new javax.swing.JPanel();
        jp_titulo = new javax.swing.JPanel();
        jl_titulo = new javax.swing.JLabel();
        jmb_menu = new javax.swing.JMenuBar();
        jm_usuarios = new javax.swing.JMenu();
        jmi_registrar = new javax.swing.JMenuItem();
        jm_productos = new javax.swing.JMenu();
        jmi_todos = new javax.swing.JMenuItem();
        jmi_electricos = new javax.swing.JMenuItem();
        jmi_herrajes = new javax.swing.JMenuItem();
        jmi_otros = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_cuerpo.setBackground(new java.awt.Color(102, 51, 255));

        jp_titulo.setBackground(new java.awt.Color(102, 80, 255));

        jl_titulo.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(60, 0, 150));
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Bienvenido ");

        javax.swing.GroupLayout jp_tituloLayout = new javax.swing.GroupLayout(jp_titulo);
        jp_titulo.setLayout(jp_tituloLayout);
        jp_tituloLayout.setHorizontalGroup(
            jp_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tituloLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );
        jp_tituloLayout.setVerticalGroup(
            jp_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_cuerpoLayout = new javax.swing.GroupLayout(jp_cuerpo);
        jp_cuerpo.setLayout(jp_cuerpoLayout);
        jp_cuerpoLayout.setHorizontalGroup(
            jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                .addComponent(jp_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_cuerpoLayout.setVerticalGroup(
            jp_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuerpoLayout.createSequentialGroup()
                .addComponent(jp_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 388, Short.MAX_VALUE))
        );

        getContentPane().add(jp_cuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));

        jm_usuarios.setText("Usuario");

        jmi_registrar.setText("Resgistrar");
        jmi_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_registrarActionPerformed(evt);
            }
        });
        jm_usuarios.add(jmi_registrar);

        jmb_menu.add(jm_usuarios);

        jm_productos.setText("Productos");

        jmi_todos.setText("Todos");
        jmi_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_todosActionPerformed(evt);
            }
        });
        jm_productos.add(jmi_todos);

        jmi_electricos.setText("Electricos");
        jmi_electricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_electricosActionPerformed(evt);
            }
        });
        jm_productos.add(jmi_electricos);

        jmi_herrajes.setText("Herrrajes");
        jm_productos.add(jmi_herrajes);

        jmi_otros.setText("Otros");
        jmi_otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_otrosActionPerformed(evt);
            }
        });
        jm_productos.add(jmi_otros);

        jmb_menu.add(jm_productos);

        setJMenuBar(jmb_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_otrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_otrosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OtrosGUI ogui = new OtrosGUI();
                ogui.setVisible(true);
                switch(tipo_usuario){
                    case "A":
                        break;
                    case "V":
                        ogui.getJtf_nombre().setEnabled(false);
                        ogui.getJtf_serial().setEnabled(false);
                        ogui.getJtf_color().setEnabled(false);
                        ogui.getJtf_marca().setEnabled(false);
                        ogui.getJtf_material().setEnabled(false);
                        ogui.getJtf_demanda().setEnabled(false);
                        ogui.getJtf_costo_produccion().setEnabled(false);
                        ogui.getJtf_costo_almacenamiento().setEnabled(false);
                        ogui.getJtf_bodega().setEnabled(false);
                        break;
                    case "B":
                        ogui.getJtf_nombre().setEnabled(false);
                        ogui.getJtf_serial().setEnabled(false);
                        ogui.getJtf_color().setEnabled(false);
                        ogui.getJtf_marca().setEnabled(false);
                        ogui.getJtf_material().setEnabled(false);
                        ogui.getJtf_demanda().setEnabled(false);
                        ogui.getJtf_costo_produccion().setEnabled(false);
                        ogui.getJtf_precio_venta().setEnabled(false);
                        ogui.getJtf_costo_almacenamiento().setEnabled(false);
                        break;
                    case "C":
                        ogui.getJtf_nombre().setEnabled(false);
                        ogui.getJtf_serial().setEnabled(false);
                        ogui.getJtf_color().setEnabled(false);
                        ogui.getJtf_marca().setEnabled(false);
                        ogui.getJtf_material().setEnabled(false);
                        ogui.getJtf_demanda().setEnabled(false);
                        ogui.getJtf_costo_produccion().setEnabled(false);
                        ogui.getJtf_precio_venta().setEnabled(false);
                        ogui.getJtf_costo_almacenamiento().setEnabled(false);
                        ogui.getJtf_bodega().setEnabled(false);
                        break;
                    default:
                        break;
                }
                
            }
        });
    }//GEN-LAST:event_jmi_otrosActionPerformed

    private void jmi_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_registrarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UsuarioGUI ugui = new UsuarioGUI();
                ugui.setVisible(true);
                
            }
        });
    }//GEN-LAST:event_jmi_registrarActionPerformed

    private void jmi_electricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_electricosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_electricosActionPerformed

    private void jmi_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_todosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoGUI pgui = new ProductoGUI();
                pgui.setVisible(true);
                switch(tipo_usuario){
                    case "A":
                        break;
                    case "V":
                        pgui.getJtf_nombre().setEnabled(false);
                        pgui.getJtf_serial().setEnabled(false);
                        pgui.getJtf_color().setEnabled(false);
                        pgui.getJtf_marca().setEnabled(false);
                        pgui.getJtf_material().setEnabled(false);
                        pgui.getJtf_demanda().setEnabled(false);
                        pgui.getJtf_costo_produccion().setEnabled(false);
                        pgui.getJtf_costo_almacenamiento().setEnabled(false);
                        pgui.getJtf_bodega().setEnabled(false);
                        break;
                    case "B":
                        pgui.getJtf_nombre().setEnabled(false);
                        pgui.getJtf_serial().setEnabled(false);
                        pgui.getJtf_color().setEnabled(false);
                        pgui.getJtf_marca().setEnabled(false);
                        pgui.getJtf_material().setEnabled(false);
                        pgui.getJtf_demanda().setEnabled(false);
                        pgui.getJtf_costo_produccion().setEnabled(false);
                        pgui.getJtf_precio_venta().setEnabled(false);
                        pgui.getJtf_costo_almacenamiento().setEnabled(false);
                        break;
                    case "C":
                        pgui.getJtf_nombre().setEnabled(false);
                        pgui.getJtf_serial().setEnabled(false);
                        pgui.getJtf_color().setEnabled(false);
                        pgui.getJtf_marca().setEnabled(false);
                        pgui.getJtf_material().setEnabled(false);
                        pgui.getJtf_demanda().setEnabled(false);
                        pgui.getJtf_costo_produccion().setEnabled(false);
                        pgui.getJtf_precio_venta().setEnabled(false);
                        pgui.getJtf_costo_almacenamiento().setEnabled(false);
                        pgui.getJtf_bodega().setEnabled(false);
                        break;
                    default:
                        break;
                }
                
            }
        });
    }//GEN-LAST:event_jmi_todosActionPerformed

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JLabel getJl_titulo() {
        return jl_titulo;
    }

    public void setJl_titulo(JLabel jl_titulo) {
        this.jl_titulo = jl_titulo;
    }

    public JMenu getJm_productos() {
        return jm_productos;
    }

    public void setJm_productos(JMenu jm_productos) {
        this.jm_productos = jm_productos;
    }

    public JMenu getJm_usuarios() {
        return jm_usuarios;
    }

    public void setJm_usuarios(JMenu jm_usuarios) {
        this.jm_usuarios = jm_usuarios;
    }

    public JMenuBar getJmb_menu() {
        return jmb_menu;
    }

    public void setJmb_menu(JMenuBar jmb_menu) {
        this.jmb_menu = jmb_menu;
    }

    public JMenuItem getJmi_electricos() {
        return jmi_electricos;
    }

    public void setJmi_electricos(JMenuItem jmi_electricos) {
        this.jmi_electricos = jmi_electricos;
    }

    public JMenuItem getJmi_herrajes() {
        return jmi_herrajes;
    }

    public void setJmi_herrajes(JMenuItem jmi_herrajes) {
        this.jmi_herrajes = jmi_herrajes;
    }

    public JMenuItem getJmi_otros() {
        return jmi_otros;
    }

    public void setJmi_otros(JMenuItem jmi_otros) {
        this.jmi_otros = jmi_otros;
    }

    public JMenuItem getJmi_registrar() {
        return jmi_registrar;
    }

    public void setJmi_registrar(JMenuItem jmi_registrar) {
        this.jmi_registrar = jmi_registrar;
    }

    public JMenuItem getJmi_todos() {
        return jmi_todos;
    }

    public void setJmi_todos(JMenuItem jmi_todos) {
        this.jmi_todos = jmi_todos;
    }

    public JPanel getJp_cuerpo() {
        return jp_cuerpo;
    }

    public void setJp_cuerpo(JPanel jp_cuerpo) {
        this.jp_cuerpo = jp_cuerpo;
    }

    public JPanel getJp_titulo() {
        return jp_titulo;
    }

    public void setJp_titulo(JPanel jp_titulo) {
        this.jp_titulo = jp_titulo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JMenu jm_productos;
    private javax.swing.JMenu jm_usuarios;
    private javax.swing.JMenuBar jmb_menu;
    private javax.swing.JMenuItem jmi_electricos;
    private javax.swing.JMenuItem jmi_herrajes;
    private javax.swing.JMenuItem jmi_otros;
    private javax.swing.JMenuItem jmi_registrar;
    private javax.swing.JMenuItem jmi_todos;
    private javax.swing.JPanel jp_cuerpo;
    private javax.swing.JPanel jp_titulo;
    // End of variables declaration//GEN-END:variables
}
